apiVersion: v1
kind: Namespace
metadata:
  name: aws-ecr-credentials-updater
  labels:
    name: aws-ecr-credentials-updater
--
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aws-ecr-credentials-updater-service-account
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: aws-authorization-cluster-role
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create", "delete"]
  - apiGroups: [""]
    resources: ["serviceaccounts"]
    verbs: ["patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: role-aws-authorization-binding
roleRef:
  apiGroup: ""
  kind: ClusterRole
  name: aws-authorization-cluster-role
subjects:
  - kind: ServiceAccount
    name: aws-ecr-credentials-updater-service-account
    namespace: aws-ecr-credentials-updater
